### ISSUE TITLE
Write section on users, groups and permissions in 01-command-line.Rmd

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/compbio-fundamentals#4]
Title in place.

**Comment by DiegoBrambilla** [comment]
Added remark under chapter "File System" and put some considerations in the chapter "Symbolic links -- *symlinks*"

**Comment by erikrikarddaniel** [comment]
Fixed in f40d1d1b043f15a9754b8d47b03bf78794f6042c.
